version: '3.4'

services:
  httpd:
    image: nouchka/sqlite3
    volumes:
      - ../buttstickerapi:/bin/buttstickerapi:ro
      - ../assets/ticker.db:/usr/share/tickerdata/ticker.db
      - ../web:/usr/share/web:ro
    networks:
      - net
    expose:
      - "8080"
    environment:
      - VIRTUAL_HOST=buttsticker.byteporter.com
      - VIRTUAL_PORT=8080
      - LETSENCRYPT_HOST=buttsticker.byteporter.com
      - LETSENCRYPT_EMAIL=webmaster@byteporter.com
    entrypoint: ["/bin/buttstickerapi"]
    restart: always

networks:
  net:
    external:
      name: docker-reverse-proxy_net
